#  CLIENT_ID=;CLIENT_SECRET=;DBMS_CONNECTION="jdbc:mysql://localhost:3306/test?sslMode=REQUIRED";DBMS_PASSWORD=;DBMS_USERNAME=root;DDL_AUTO=update;FRONTEND_URL=http://localhost:5173;REDIS_HOST=localhost;REDIS_PORT=6379;SECURE=false;SIGNER_KEY="bXktc3VwZXItbG9uZy1zZWNyZXQta2V5LWZvci1qc3ctaHM1MTItc2VjdXJlLXRva2VuLWFwcGxpY2F0aW9uLTIwMjY=";SMTP_EMAIL=;SMTP_HOST=smtp.gmail.com;SMTP_PASSWORD=

server:
  forward-headers-strategy: framework
  port: 8080
  servlet:
    session:
      cookie:
        same-site: lax

app:
  frontend-url: ${FRONTEND_URL}
  cookie:
    secure: ${SECURE}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: it-iap
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  signerKey: ${SIGNER_KEY}
