server:
  port: 8080

spring:
  application:
    name: test
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: false
  security:
    admin-full-permission: true
  output:
    ansi:
      enabled: ALWAYS

jwt:
  singerKey: ${SINGER_KEY}
